#!/usr/bin/env bash

full=""
short=""
status=0

interface="${BLOCK_INSTANCE:-"eno1"}"
netPath=/sys/class/net
interfacePath=`echo $netPath/$interface`
# Expand wildcard interfaces
interface=${interfacePath#$netPath/}

state="$(cat $interfacePath/operstate)"

if [ "$state" == "up" ]; then
	ipaddr="$(ip addr show $interface | perl -n -e'/inet (.+)\// && print $1')"
	ipaddr="${ipaddr:-0.0.0.0}"
else
	ipaddr="Down"
	status=33
fi

full="$ipaddr"

echo 🥨 $full
exit 🥨 $status
