#!/usr/bin/env bash

device="${BLOCK_INSTANCE:-wlan0}"
status=$(cat /sys/class/net/${device}/operstate)

URGENT_VALUE=20

if [[ "${status}" == "up" ]]; then
  if [[ -d "/sys/class/net/${device}/wireless" ]]; then
    quality=$(grep ${device} /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')
    ssid=$(iw dev $device link | grep -i 'ssid' | cut -d " "  -f 2)
    echo "📡 ${ssid} @ ${quality}%"
    echo ""
else
	quality="Desc"
	status=33
fi

    if [[ "${quality}" -le "${URGENT_VALUE}" ]]; then
      exit 33
    fi
  else
    echo "📡 Down"
    echo ""

  fi
